import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/provider/ToastProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OJTCONNECT",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
  return (
    
    <html lang="en">
      <body className={`${inter.className} backgoundGradient`} style={{scrollBehavior:'smooth'}}>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
   
    
  );
}
